### ISSUE TITLE
Nice blog post about how to speed up h2o::as.h2o()

### ISSUE THREAD

**Issue by ledell** [ellisp/ellisp.github.io#40]
Hi Peter,
We have had some complaints that `h2o::as.h2o()` is very slow for sparse matrices and so we came across your [awesome blog post](https://ellisp.github.io/blog/2017/02/18/svmlite) on the topic.  We are [planning to](https://0xdata.atlassian.net/browse/PUBDEV-4630?filter=-2) implement your solution (unless you wanted to submit a PR directly).  

Thanks!
-Erin

**Comment by ellisp** [comment]
Hi, great to hear that it was useful!  I only just saw this issue (have not really been monitoring GitHub in my last job) and presume you have it all sorted now.

**Comment by ledell** [comment]
@ellisp We added some of your code to H2O [here](https://github.com/h2oai/h2o-3/blob/5a6d4c7f3bb556d905127aac621a2ed1bc499581/h2o-r/h2o-package/R/frame.R#L3265).  I think there was a bug in it that got fixed as well.  Thanks again!

**Comment by rgayler** [comment]
Thank, Peter. All sorted. I ended up not using the NZIS SURF data in the
conference presentation, but the acknowledgements are in my code in case I
ever change my mind.

Ross
