### ISSUE TITLE
Preferred form of attribution

### ISSUE THREAD

**Issue by rgayler** [ellisp/ellisp.github.io#41]
Hi Peter,
I am putting together a conference presentation and want to use some of your code in it (e.g. the code from https://ellisp.github.io/blog/2015/08/15/importing-nzis-surf). Your blog material is licensed as CC-BY-SA. Do you have a preferred form for attribution?
Cheers
Ross

**Comment by ellisp** [comment]
Off-line I agreed so long as it mentions me, the URL, the blog title and Peter's Stats Stuff it is ok.  I need to decide something and put it on the site.

Ross suggested: 

Unless something else turns up I'll probably cite it in the form from the Statistics NZ style guide (http://www.stats.govt.nz/about_us/what-we-do/our-publications/style-guides/style-manual/reference-examples.aspx)

Given that you specify a CC-BY it would be nice if you also gave the preferred attribution on your site, like this: http://www.stats.govt.nz/about_us/about-this-site/copyright-terms-of-use.aspx
