### ISSUE TITLE
Hi and thanks

### ISSUE THREAD

**Issue by Afyers** [ellisp/ellisp.github.io#42]
Hi Peter, I'm not sure if this is the best place to do this, but I just wanted to touch base and say hi. 

I'm a reporter with Fairfax and I'm going to be doing a lot of reporting on polls, voting demographics, geography etc in the coming weeks and have found your blog to be a brilliant resource. 

I'm currently delving into the NZES and am hoping to do some reporting on that leading up to the election. I code in Python mostly, so sadly I may not be able to make best use of you Relect package - perhaps I will have to upskill and learn some more R in time for 2020. 

Anyway I just wanted to get in touch given we seem to be interested in similar datasets and to say thanks for the excellent work. 

Cheers, 
Andy Fyers

**Comment by ellisp** [comment]
Thanks for the feedback!  Stay in touch.
