### ISSUE TITLE
Missing "overall outcomes" chart for Model A

### ISSUE THREAD

**Issue by drmead** [ellisp/ellisp.github.io#43]
Hi, The 'overall outcomes' chart for Model A seems to have gone missing in the last couple of days. The equivalent on Model B is still there. Thanks for the good work! I suspect that the predictive capabilities of the models will be being severely challenged by the rapid rates of change in voter intentions. Cheers, Derek

**Comment by ellisp** [comment]
Thanks, there is something funny about that chart getting corrupted occasionally.  It seems to be fixed for now.
