### ISSUE TITLE
StatsBlogs

### ISSUE THREAD

**Issue by AntoineSoetewey** [ellisp/ellisp.github.io#47]
Dear Peter,

On your [about page](http://freerangestats.info/about/) you mention StatsBlogs. The URL [statsblogs.com](http://statsblogs.com/) seems to be broken. By any chance, do you know if they moved their blog to another URL or if they simply stopped their activity?

I'd be interested to read their blog if it is still available.

Thanks in advance.
Best,
Antoine

**Comment by ellisp** [comment]
Thanks. I used to read them but haven't for a while. I will pull that from the links on my page.

I tried to get my own blog listed in their feed and never got any responses from any means of communicating, so i'm not astonished if they have just run out of oomph and stopped.
