### ISSUE TITLE
Correction request for Fixing scientific publishing and peer review blog

### ISSUE THREAD

**Issue by michaelstacey** [ellisp/ellisp.github.io#49]
Dear Peter,

On your post: Fixing scientific publishing and peer review, you refer to a retraction in Nature on the mental health impact of gaming in Africa (second paragraph). However, the retraction was in the journal Scientific Reports. Please could you correct the blog post accordingly?

Kind Regards
Michael

**Comment by ellisp** [comment]
Sorry for this. I had assumed that because it was [on the Nature website](https://www.nature.com/articles/s41598-020-66798-w) it was in Nature.

I have corrected this, it should show up in the published version in about half an hour.
