### ISSUE TITLE
Need some advice on restricted binning data

### ISSUE THREAD

**Issue by asif2526** [ellisp/ellisp.github.io#52]
Respected Sir,
I am Dr. Asif and I am from Bangladesh. I am an epidemiology student and learning infectious disease modelling with R. I am currently working as surveillance officer in Communicable disease Control ,DGHS . We are trying to write a paper on Covid-19 fatalities according to age and gender. But due to very restricted data source I am having some problem. After reading your blog I believe I really need your Suggestion and help. I am trying to contact with you through your e-mail but cant get any, and I have also tried to communicate with you in linked in. I really need your valuable help.

Sincerely
Dr. K.M. Rukhsad Asif Zaman

**Comment by ellisp** [comment]
Responded via email.
