### ISSUE TITLE
Dynamic Stochastic General Equilibrium Mode

### ISSUE THREAD

**Issue by SamDeegan** [ellisp/ellisp.github.io#54]
Hi Peter,

Apologies for the impromptu email, but I came across your article on the DSGE model (link below) from five years ago. I was interested in acquiring the source code to see how you modified the base Smets-Wouters model. The current source code link appears broken. 

I have recently studied DSGE models, and more or less, mirroring your path, I wanted to take the model apart in R to learn more about it. I would eventually like to re-parameterise it using Bayesian techniques to gain experience for a central bank/department of finance role. 

Thank you for taking the time to read my email, and I appreciate the blog post. It was beneficial, particularly the links to other resources. 

Many thanks, 
Sam

Link to the original post: http://freerangestats.info/blog/2016/02/20/DSGE

**Comment by ellisp** [comment]
thanks for the feedback. I will fix the code in the post. In the mean time, that broken link should be pointing to:

https://github.com/ellisp/blog-source/tree/master/_working/_output/0031-shiny

**Comment by ellisp** [comment]
should now be fixed.
