### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by JBarsotti** [ellisp/ellisp.github.io#55]
Hi Mr. Ellis,

I just wanted to thank you for some code you wrote on StackExchange a while ago. It was about the best ways to show error bounds on radar mappings. I would like to use it in an app I am creating for a research project, and I would like to know if you have any preferred way of being acknowledged for your hard work?

Thanks again!

**Comment by ellisp** [comment]
Hi, no particular preferred way so long as I am mentioned by name, thanks.
