### ISSUE TITLE
Question re data in our business

### ISSUE THREAD

**Issue by rickaubt** [ellisp/ellisp.github.io#56]
Hi there, I saw your profile on LinkedIn and I was inspired to reach out to you.  I'm involved with a global corporate not-for-profit, and I know that we need to do more with data (but don't know where to start!).
We have screeds of data, but doing sweet nothing with it.

Is this something that you could help us on?

Thanks, Rick Anderson, UBT.  rick.anderson@ubteam.com +64 21 228 3931

**Comment by ellisp** [comment]
Responded via LinkedIn.
